---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
library(stringi)
library(tidyr)
library(zoo)
library(ggplot2)
library(ggfortify)
library(lubridate)
library(xts)
library(forecast)
```

```{r}
dir_df1 <- "/Users/martinagulino/Desktop/DataScience/1 anno/2 semestre/DataScience Lab/Progetto/ElData/UKPX_1215_Price_byhour.csv"
dir_df2 <- "/Users/martinagulino/Desktop/DataScience/1 anno/2 semestre/DataScience Lab/Progetto/ElData/UKPX_1215_Loads_byhour.csv"

df_prezzi1 <- read.csv(dir_df1)
df_consumi1 <- read.csv(dir_df2)
```


```{r}
hour <- c(01:24)
appo1 <- data.frame()

for (j in 2:ncol(df_prezzi1)) {
  for (i in 1:nrow(df_prezzi1)) {
    if(j%%2 == 0){
      appo1[i,j/2] <- (df_prezzi1[i,j]+df_prezzi1[i,j+1])/2
    }
  }
}
colnames(appo1) <- paste0("H", hour)
DateYYYYMMDD <- df_prezzi1[,1]
appo1 <- cbind(DateYYYYMMDD, appo1)

df_prezzi <- appo1
df_prezzi
```


```{r}
appo2 <- data.frame()
for (j in 2:ncol(df_consumi1)) {
  for (i in 1:nrow(df_consumi1)) {
    if(j%%2 == 0){
      appo2[i,j/2] <- df_consumi1[i,j]+df_consumi1[i,j+1]
    }
  }
}  
colnames(appo2) <- paste0("H", hour)
DateYYYYMMDD <- df_consumi1[,1]
appo2 <- cbind(DateYYYYMMDD, appo2)

df_consumi  <- appo2
```


```{r}
df_prezzi$anno <- stri_sub(df_prezzi$DateYYYYMMDD,1,4)
df_prezzi$mese <- stri_sub(df_prezzi$DateYYYYMMDD,5,6)
df_prezzi$giorno <- stri_sub(df_prezzi$DateYYYYMMDD,7,8)
```

```{r}
df_prezzi <- df_prezzi %>% gather("ora", "prezzo", H1:H24)
df_prezzi$ora <- stri_sub(df_prezzi$ora,2,3)
df_prezzi <- df_prezzi %>% mutate(ora = paste0(ora,":00:00"))
df_prezzi$date <- as.Date(with(df_prezzi, paste(anno, mese, giorno,sep="-")), "%Y-%m-%d")
df_prezzi <- df_prezzi %>% arrange(date)
df_prezzi$dateTime = as.POSIXct(paste(df_prezzi$date,df_prezzi$ora), format="%Y-%m-%d %H:%M:%S")
df_prezzi$DateYYYYMMDD <- NULL
```

```{r}
df_prezzi
```

```{r}
df_consumi$anno <- stri_sub(df_consumi$DateYYYYMMDD,1,4)
df_consumi$mese <- stri_sub(df_consumi$DateYYYYMMDD,5,6)
df_consumi$giorno <- stri_sub(df_consumi$DateYYYYMMDD,7,8)

df_consumi <- df_consumi %>% gather("ora", "consumo", H1:H24)
df_consumi$ora <- stri_sub(df_consumi$ora,2,3)
df_consumi <- df_consumi %>% mutate(ora = paste0(ora,":00:00"))
df_consumi$date <- as.Date(with(df_consumi, paste(anno, mese, giorno,sep="-")), "%Y-%m-%d")
df_consumi <- df_consumi %>% arrange(date)
df_consumi$dateTime = as.POSIXct(paste(df_consumi$date,df_consumi$ora), format="%Y-%m-%d %H:%M:%S")
df_consumi$DateYYYYMMDD <- NULL
```

```{r}
df_consumi
```

```{r}
summary(df_prezzi)
```

```{r}
summary(df_consumi)
```


```{r}
totale
totale <- left_join(df_prezzi, df_consumi, by = c("anno" = "anno", "mese" = "mese", "giorno"="giorno", "ora"="ora"))
totale <- totale[, -c(9:10)]
totale
```
Controllo i NA
```{r}
apply(totale, 2, function(x) any(is.na(x)))
apply(totale, 2, function(x) any(is.nan(x)))
summary(totale)
```
Si vede che ci sono dei Na in dateTime.x. Per calcolare quanti sono facciamo:
```{r}
apply(is.na(totale),2,sum)
```
Quindi risultano essere 4. 
```{r}
which(is.na(df_prezzi$dateTime))
which(is.na(df_consumi$dateTime))
```
Creo un dataset per ogni anno.
```{r}
lista_anni <- c(2012,2013,2014,2015)
datasets <- list()
for(i in lista_anni){
  df_prezzi %>% filter(anno==i) -> x
  assign(paste0('df_anno_prezzi_',i), x)
  datasets <- append(datasets,paste0('df_anno_prezzi',i))
}
```
Sposto la colonna data all'inizio. 
```{r}
df_anno_prezzi_2012 <- df_anno_prezzi_2012 %>%
  select(date, everything())
df_anno_prezzi_2013 <- df_anno_prezzi_2013 %>%
  select(date, everything())
df_anno_prezzi_2014 <- df_anno_prezzi_2014 %>%
  select(date, everything())
df_anno_prezzi_2015 <- df_anno_prezzi_2015 %>%
  select(date, everything())
```

Inizio con il 2012:
```{r}
df_anno_prezzi_2012$ID <- seq.int(nrow(df_anno_prezzi_2012))
summary(df_anno_prezzi_2012$dateTime)
#c'è un NaN
which(is.na(df_anno_prezzi_2012$dateTime))
#nella posizione numero 2018
new_DF<-subset(df_anno_prezzi_2012,is.na(df_anno_prezzi_2012$dateTime)) #prende l'intersezione tra questi due dataset
# 2012-03-25 2:00:00 in questo modo ho capito con che cosa sostituire il NaN
df_anno_prezzi_2012[is.na(df_anno_prezzi_2012)] <- as.POSIXct("2012-03-25 02:00:00")
summary(df_anno_prezzi_2012)
df_anno_prezzi_2012[2018,]
```
Guardo ora il 2013:
```{r}
df_anno_prezzi_2013$ID <- seq.int(nrow(df_anno_prezzi_2013))
summary(df_anno_prezzi_2013$dateTime)
#c'è un NaN
which(is.na(df_anno_prezzi_2013$dateTime))
#nella posizione numero 2018
new_DF<-subset(df_anno_prezzi_2013,is.na(df_anno_prezzi_2013$dateTime)) #prende l'intersezione tra questi due dataset
new_DF
# 2013-03-31 2:00:00 in questo modo ho capito con che cosa sostituire il NaN
df_anno_prezzi_2013[is.na(df_anno_prezzi_2013)] <- as.POSIXct("2013-03-31 02:00:00")
summary(df_anno_prezzi_2012)
df_anno_prezzi_2013[2138,]
```
Guardo il 2014:
```{r}
df_anno_prezzi_2014$ID <- seq.int(nrow(df_anno_prezzi_2014))
summary(df_anno_prezzi_2014$dateTime)
#c'è un NaN
which(is.na(df_anno_prezzi_2014$dateTime))
#nella posizione numero 2018
new_DF<-subset(df_anno_prezzi_2014,is.na(df_anno_prezzi_2014$dateTime)) #prende l'intersezione tra questi due dataset
new_DF
# 2014-03-31 2:00:00 in questo modo ho capito con che cosa sostituire il NaN
df_anno_prezzi_2014[is.na(df_anno_prezzi_2014)] <- as.POSIXct("2014-03-31 02:00:00")
summary(df_anno_prezzi_2014)
df_anno_prezzi_2014[2138,]
```
Guardo il 2015:

```{r}
df_anno_prezzi_2015$ID <- seq.int(nrow(df_anno_prezzi_2015))
summary(df_anno_prezzi_2015$dateTime)
#c'è un NaN
which(is.na(df_anno_prezzi_2015$dateTime))
#nella posizione numero 2018
new_DF<-subset(df_anno_prezzi_2015,is.na(df_anno_prezzi_2015$dateTime)) #prende l'intersezione tra questi due dataset
new_DF
# 2015-03-29 2:00:00 in questo modo ho capito con che cosa sostituire il NaN
df_anno_prezzi_2015[is.na(df_anno_prezzi_2015)] <- as.POSIXct("2013-03-31 02:00:00")
summary(df_anno_prezzi_2012)
df_anno_prezzi_2015[2090,]
```

```{r}
totale_ID<- rbind(df_anno_prezzi_2012, df_anno_prezzi_2013, df_anno_prezzi_2014, 
               df_anno_prezzi_2015)
```

```{r}
totale_ID %>% group_by(date, anno, ID) %>%  # raggruppo
  summarise(prezzo= sum(prezzo)) %>%        # sintetizzo
  arrange(anno, date) %>%                   # ordino
  ungroup() -> totale_anno_somma 
totale_ID
```

```{r}
totale_ID %>% group_by(date, anno, ID) %>% summarise(prezzo) %>%
  ggplot(aes(x = ID, y = prezzo, color = anno)) +
  geom_line()
```

```{r}
gennaio <- totale_ID %>% filter(mese=="01")
gennaio %>% group_by(date, anno, ID) %>% summarise(prezzo) %>%
  ggplot(aes(x = ID, y = prezzo, color = anno)) +
  geom_line()
```

```{r}
primavera <- totale_ID %>% filter(mese=="01" & mese=="01" & mese=="01" & mese=="01")
primavera %>% group_by(date, anno, ID) %>% summarise(prezzo) %>%
  ggplot(aes(x = ID, y = prezzo, color = anno)) +
  geom_line()
```


```{r}
new_DF<-subset(totale,is.na(totale$dateTime.x))

 

# ci sono 4 date da sistemare inizio dalla prima
# 2012   03     25 02:00:00
# 2013   03     31 02:00:00
# 2014   03     30 02:00:00
# 2015   03     29 02:00:00
totale %>% mutate(dateTime.x = if_else((giorno =="25") & (anno == "2012") & (mese == "03") & (ora=="02:00:00"), as.POSIXct("2012-03-25 02:00:00"), dateTime.x)) -> totale 
```

